disease_dic = {
    'Apple___Apple_scab': "Apple scab is a fungal disease. Use fungicides and remove infected leaves.",
    'Apple___Black_rot': "Black rot affects apples. Prune and destroy infected parts.",
    'Apple___Cedar_apple_rust': "Use resistant varieties and remove nearby juniper trees.",
    'Apple___healthy': "Your apple plant is healthy!",
    'Blueberry___healthy': "Your blueberry plant is healthy!",
    'Cherry_(including_sour)___Powdery_mildew': "Apply sulfur-based fungicides to control powdery mildew.",
    'Cherry_(including_sour)___healthy': "Your cherry plant is healthy!",
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': "Use fungicides and rotate crops.",
    'Corn_(maize)___Common_rust_': "Use rust-resistant corn varieties.",
    'Corn_(maize)___Northern_Leaf_Blight': "Apply fungicides and practice crop rotation.",
    'Corn_(maize)___healthy': "Your corn plant is healthy!",
    'Grape___Black_rot': "Remove infected grapes and use fungicides.",
    'Grape___Esca_(Black_Measles)': "Avoid pruning during wet weather and remove infected vines.",
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': "Use fungicide sprays and proper spacing.",
    'Grape___healthy': "Your grapevine is healthy!",
    'Orange___Haunglongbing_(Citrus_greening)': "No cure exists. Remove and destroy infected trees.",
    'Peach___Bacterial_spot': "Use copper-based sprays to manage bacterial spot.",
    'Peach___healthy': "Your peach plant is healthy!",
    'Pepper,_bell___Bacterial_spot': "Use disease-free seeds and copper sprays.",
    'Pepper,_bell___healthy': "Your bell pepper plant is healthy!",
    'Potato___Early_blight': "Apply fungicides and avoid overhead watering.",
    'Potato___Late_blight': "Use resistant varieties and fungicide treatments.",
    'Potato___healthy': "Your potato plant is healthy!",
    'Raspberry___healthy': "Your raspberry plant is healthy!",
    'Soybean___healthy': "Your soybean plant is healthy!",
    'Squash___Powdery_mildew': "Use sulfur or neem oil to treat powdery mildew.",
    'Strawberry___Leaf_scorch': "Use fungicides and proper spacing to reduce humidity.",
    'Strawberry___healthy': "Your strawberry plant is healthy!",
    'Tomato___Bacterial_spot': "Use copper-based sprays and avoid working with wet plants.",
    'Tomato___Early_blight': "Apply chlorothalonil or copper-based fungicides.",
    'Tomato___Late_blight': "Remove infected plants immediately and apply fungicides.",
    'Tomato___Leaf_Mold': "Improve air circulation and apply fungicides.",
    'Tomato___Septoria_leaf_spot': "Use fungicides and avoid overhead watering.",
    'Tomato___Spider_mites Two-spotted_spider_mite': "Use miticides or insecticidal soap.",
    'Tomato___Target_Spot': "Rotate crops and apply fungicides.",
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus': "Control whiteflies and use virus-resistant varieties.",
    'Tomato___Tomato_mosaic_virus': "Remove and destroy infected plants.",
    'Tomato___healthy': "Your tomato plant is healthy!"
}
